name: CI
on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  macos_build:
    name: MacOS
    strategy:
      fail-fast: true
      matrix:
        os: [macos-14, macos-15, macos-15-intel, macos-26, macos-26-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          brew tap coursier/formulas .
          brew install coursier
          brew test coursier
