name: CI
on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  macos_build:
    name: MacOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          brew tap coursier/formulas .
          brew install coursier
          brew test coursier
